-- Create tables
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  permissions JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  city TEXT,
  phone TEXT,
  email TEXT,
  total_orders INT DEFAULT 0,
  total_spent NUMERIC DEFAULT 0
);

CREATE TABLE team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL,
  status TEXT DEFAULT 'ativo'
);

CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  client_name TEXT NOT NULL,
  voltage TEXT,
  deadline DATE,
  seller TEXT,
  total_price NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'aguardando',
  created_at DATE DEFAULT CURRENT_DATE,
  priority BOOLEAN DEFAULT FALSE,
  items JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE production (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id TEXT NOT NULL,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  cutter TEXT,
  tailor TEXT,
  prep TEXT,
  assembler TEXT,
  cut_done BOOLEAN DEFAULT FALSE,
  tailor_done BOOLEAN DEFAULT FALSE,
  prep_done BOOLEAN DEFAULT FALSE,
  assemble_done BOOLEAN DEFAULT FALSE,
  done BOOLEAN DEFAULT FALSE
);

CREATE TABLE finalization (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id TEXT NOT NULL,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  finalizer TEXT,
  done BOOLEAN DEFAULT FALSE,
  fin_date DATE
);

-- Initial Data Seed
INSERT INTO users (name, email, password, role, permissions) VALUES
('Admin', 'admin', 'ags', 'admin', '["orders","production","finalization","dashboard","clients","team"]'),
('Miriane', 'miriane', '123', 'miriane', '["orders","production","finalization","clients"]'),
('Produção', 'producao', '123', 'producao', '["production","finalization"]'),
('Finalização', 'finalizacao', '123', 'finalizacao', '["finalization"]');

INSERT INTO clients (name, city, phone, email) VALUES
('Festa Kids LTDA', 'São Paulo', '(11) 99999-0001', 'contato@festakids.com'),
('Parque Alegria', 'Campinas', '(19) 98888-0002', 'parque@alegria.com');

INSERT INTO team (name, role) VALUES
('Maria Costa', 'Costura'),
('Carlos Lima', 'Corte'),
('Ana Souza', 'Preparação'),
('Luan', 'Vendedor'),
('Fernanda Reis', 'Costura'),
('Emerson', 'Vendedor'),
('Sidnei', 'Vendedor'),
('Roberto Santos', 'Preparação'),
('Joana Melo', 'Finalizador');
